---
# Kubeconfig setup tasks

- name: Create kube directory
  ansible.builtin.file:
    mode: '0700'
    path: ~/.kube
    state: directory

- name: Copy kubeconfig
  ansible.builtin.copy:
    dest: ~/.kube/config
    mode: '0600'
    remote_src: true
    src: /etc/rancher/k3s/k3s.yaml
