apiVersion: ENC[AES256_GCM,data:eQQ=,iv:/qlcY42qFfTSIuxti4SlUvtvY/HDhg+sMS/LaI+NU3Q=,tag:WkRgLaB4XyVZMVlXk6ppyg==,type:str]
kind: ENC[AES256_GCM,data:ds/1v861,iv:Ppsxn5c9fawayx4pG9k7AN/lZEtnPt2TSYLZZMrpRqo=,tag:BLixXc3m8HkHE4eQIEWO7A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qKuhpqZiFIcRFasoCpWZurwiTbeH6erwWQ==,iv:mjpYJh73iROid6r6t/2uXdSdxw8kvdEU6HmlJ66TcCg=,tag:2EEgXhjhYANQDcij09aNtA==,type:str]
    namespace: ENC[AES256_GCM,data:K0IqfXnPrBB7BHbR9A==,iv:F0HfN9FyPrpyE/bNlASa6UHpKZMgoxlbWyBnFbxN1H8=,tag:yQJP1kNePcwpQwe7sH61fw==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:xQx44/VtB6PgB/HCa8J9Pj8ae1zf5A==,iv:HI/stR2V/T4Q9iLKFOK6Mz4jBakZWhkCfp4LmlmBzFM=,tag:HX0VluAP/sFqSeKCk1nsMQ==,type:str]
type: ENC[AES256_GCM,data:8OzxVzZW,iv:OydjEeKfnZhEKUawSp8M5CjgiqjBEq3FYKclMFqljdE=,tag:aovT7+2xXbbtR1PhekdeFg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:428207760481:key/f7eafd84-0824-4c61-9a23-f6a296b95c6e
          created_at: "2026-02-04T20:30:33Z"
          enc: AQICAHhrUGVr9NJvwLREhre55EQ8AoXq2mH+hNU49tVyqlFy0AH0M83CYtmwsz8Rj0WktxqPAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCK0RSxHyVvvlVP6dAgEQgDtr1Up3FSaCDkOLprEV0FhPfZngmVBUMjNUR26Uc5LVkSz7meAUG5AydygodhAEYorCugxZyGk0E/I3mw==
          aws_profile: ""
    lastmodified: "2026-02-04T20:30:34Z"
    mac: ENC[AES256_GCM,data:nU3X6JH9NCBVyKnBv5okWPm2HFYkN5cguCkXXET3dqli/maG+IVJiBCs7QvAyDB6+e0aMJ0BApn2B2F0CK7G5NkZMuJGLj+SziiVtBzmj1U9uU+4tsQU34F9IBMCiyVhTfoAJujkCYG1OM1vcLgBZ8MeTNjoq0mLnAezQuShl+g=,iv:U/qD+0xc70O0k4VhSFZ5vNTq4Ie/Jz3aKmAl2D1j/Uk=,tag:ux89zE9E5x7OCgQoSRB8Cg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
