#ENC[AES256_GCM,data:eC8wCVbKpeJHa7DZFlTw48O8+kw7AVEXlxpE5Y6AAQI3nWjop5PFd2HSPe+ujoOpi7atixjttpFYEeMjEQFOdf2x9QSPi+MO1m7xkX5xydsuYX5z9w==,iv:L9biwDBHJaiGsn307jW/g9rPwCno6qQQh1XpBP649+k=,tag:bnb4O3HxgJh/8o4xYR3hAA==,type:comment]
wireguard_private_key: ENC[AES256_GCM,data:xwwSBU2QbtI2hqnOwn7PM/IcKDW10LVKmu3JGyEhgOEbCBT8HDLRxU+WBW4=,iv:PP2HFrwV62Tn3rpGolgkboDdf4lGjN2HS8eTvErh+Ws=,tag:fznV1cTyNRckLOeJ4EosWQ==,type:str]
wireguard_peers:
    - public_key: ENC[AES256_GCM,data:+4jDAfJjOzFKAm9gC936qqErMuVIKGjsquEbHwHGEPdY6w2qDfWR+iCxXZw=,iv:VYw16lA0pMnlTzmiLjIg7bSwn9vXjkaptYxQ9BDC5nw=,tag:n3KR/XeO4f1qhFTFG1izgw==,type:str]
      allowed_ips: ENC[AES256_GCM,data:RmnafLblgr9HCXkSRnuGeD+3DZDGT0hvp27y,iv:8vgZEeXFqWC40I7HY0pBYLfMBYdVFS4Wu1NsTUBSNTM=,tag:rstluPdbRb1GwCxccqtYeQ==,type:str]
      endpoint: ENC[AES256_GCM,data:j4RlR6+GAB4aFiTvaDCqKpeVFQ==,iv:8Lvx4k9slmx73bqNfTuNwrVL5v99O6AcvNYAeUKROaM=,tag:2QOlihOOro9VzEPaIuqPhQ==,type:str]
      preshared_key: ENC[AES256_GCM,data:CMYpffh6AsfBcH/vKsuLcEhZ3EP9GabvN2I3vhqTkHoWYzVxDiuqO9ZoFVA=,iv:JLWGSe2oXTM42PQMszkvQGPc1+V3+IxLp5z7w7RVDko=,tag:brxzWHzQdUrbshPI4uVmIw==,type:str]
vault_aws_access_key_id: ENC[AES256_GCM,data:Eq/hRwdbRm/gjKMPRNWvWQn8QfU=,iv:hYL11ix91R3jwtYXfaeE0TDBKkiwDOaK5o8Dx2wgrDc=,tag:3zIEy/jA3BnMHOwFVoQbXQ==,type:str]
vault_aws_secret_access_key: ENC[AES256_GCM,data:AalIVCetYAh/oV0Ly4VJOBP+cok7B05uCxtDPHySAFqFs3/VWyFXFA==,iv:wWaYEv8SMYBqS2SDnq2+CDwq961z6GW6toMSxbOAA30=,tag:fWodVmYQE8MRH0U/nswwBg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:428207760481:key/f7eafd84-0824-4c61-9a23-f6a296b95c6e
          created_at: "2025-12-26T04:11:24Z"
          enc: AQICAHhrUGVr9NJvwLREhre55EQ8AoXq2mH+hNU49tVyqlFy0AFh8TeS981Zl1rvyMlxV9s9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3OQU0mkDVOYrjYiQAgEQgDsg18Jf6fuaXJNatfTt5wraTCXUx/hm3+8MlJ6B2nKZcWIMHkEoI+hl6t1RhoIob9KnhtCRuT8JF1zFDg==
          aws_profile: ""
    lastmodified: "2025-12-26T04:11:25Z"
    mac: ENC[AES256_GCM,data:k2PPh+NNiXd9TPgTlWTGSU0AQ+1dXGxRztuc32lLKNb9cXYSyZRQwcvIDlUMTBcmePlgOBkf5swjfGyYYb7whchHgEw6JIttAzWJaaNf5nNK3trHzUNJzpQIqVQYu//DAPG3MMoKkTy+dwPQDpMK+JxiQHYBZ+gGcEG0NQvh+nw=,iv:AMRi7fSgALnfKawPNb5O/s9i/+o7Q3TsB+dtQ4+lJWo=,tag:W4+qX0Xbs1LI9cJ61qhvow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
