apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: blocky
  namespace: argocd
spec:
  destination:
    namespace: blocky
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: blocky
    helm:
      releaseName: blocky
      valueFiles:
      - values.yaml
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: "" # Latest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
