# Blocky Configuration via Helm

config:
  upstreams:
    groups:
      default:
        - tcp-tls:1.1.1.1:853
        - tcp-tls:8.8.8.8:853

  blocking:
    blackLists:
      ads:
        - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    clientGroupsBlock:
      default:
        - ads

  prometheus:
    enable: true
    path: /metrics

  caching:
    minTime: 5m
    maxTime: 30m

service:
  type: ClusterIP
  externalIPs:
    - 10.42.0.6
